### ISSUE TITLE
Extreme Left and Right Behaviour

### ISSUE THREAD

**Issue by phet-steele** [phetsims/gravity-force-lab#42] opened 2016-01-11 17:11 UTC
Two different things happen depending if you are on the left or right side.

Left side:
1. Drag m1 and m2 as far to the left as possible with both at 1 kg.
2. Increasing the mass of m1 does not push m2 out of the way, instead it overlaps:
![1 ate 2](https://cloud.githubusercontent.com/assets/5863899/12240449/b814d456-b84a-11e5-9d03-8b2b9adba7aa.PNG)
Looks way cooler if you increase the mass of m2 before step 2:
![1 is 2](https://cloud.githubusercontent.com/assets/5863899/12240476/deb15da0-b84a-11e5-8b15-f3f74b777bc4.PNG)

Right side:
The right bound for m2 is much further to the right than it should be:
1. Drag m1 and m2 as far to the right as possible with both at 1 kg.
2. Increase the mass of m2 and the guy holding the mass will get pushed off screen. No functionality is lost, but it is a different behaviour than the left side and is why I'm reporting it.

Tested on Win 8.1 FF & Chrome.

Troubleshooting information:
Name: ‪Gravity Force Lab‬
URL: http://www.colorado.edu/physics/phet/dev/html/gravity-force-lab/1.2.0-rc.1/gravity-force-lab_en.html
Version: 1.2.0-rc.1 2016-01-08 20:53:50 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
Language: en-US
Window: 1366x643
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"d4909677","branch":"HEAD"},"axon":{"sha":"5a39ec57","branch":"HEAD"},"babel":{"sha":"ddb09d1b","branch":"master"},"brand":{"sha":"c9282935","branch":"HEAD"},"chipper":{"sha":"4e863d13","branch":"HEAD"},"dot":{"sha":"7a28b1a9","branch":"HEAD"},"gravity-force-lab":{"sha":"c8ad3e0a","branch":"HEAD"},"joist":{"sha":"aa84f2d5","branch":"HEAD"},"kite":{"sha":"4a947119","branch":"HEAD"},"phet-core":{"sha":"73a034c6","branch":"HEAD"},"phetcommon":{"sha":"d712ace0","branch":"HEAD"},"scenery":{"sha":"ace9a1cc","branch":"HEAD"},"scenery-phet":{"sha":"6898cf73","branch":"HEAD"},"sherpa":{"sha":"f6999215","branch":"HEAD"},"sun":{"sha":"5a01f87b","branch":"HEAD"},"tandem":{"sha":"873e0387","branch":"HEAD"}}

**Comment by aadish** [comment] 2016-02-16 15:45
fixed closing

**Comment by BryceAG** [comment] 2016-02-17 20:33
The right side interaction still slightly happens, but only about 1/5th of an inch using the ruler. When moving the right mass back it jumps to the correct bound. Additionally, if the right mass is pushed past the bounds, and then the left mass is reduced to the smallest mass and moved to the right bound, it is not able to be dragged left unless the mass is changed. Tested on Win 7 chrome

**Comment by BryceAG** [comment] 2016-02-17 20:34
The left mass can also be pushed 1/5th of an inch past the bounds by changing the right mass size, but the right mass can still be moved easily

**Comment by brroberts1231** [comment] 2016-02-17 20:39
Only when you click and drag on the mass itself will it not drag. If you click on the person or the string it will drag

**Comment by brroberts1231** [comment] 2016-02-17 20:42
Seems to be that the area where you can click on the red mass extends a little beyond the actual size of the mass so when you try to click on the blue mass, it is really trying to move the red one.

**Comment by BryceAG** [comment] 2016-02-19 18:58
Reproduced on Win 8 and 10 with chrome. Also @brroberts1231 is right, the problem with not sliding the left mass is due to the right mass having a larger click-box that overlaps the left mass. This can anywhere in the bounds, not just on the edges

**Comment by brroberts1231** [comment] 2016-02-19 19:38
Not related to the click-box topic above:
When you take a 1kg mass and pull it all the way to the edge and then change its size by either raising the mass or clicking constant radius, the ball will extend the 1/5 inch outside the bound without needing to be pushed by the other mass. 
The edge past which they can't be dragged is at the 1 inch mark.
![screen shot 2016-02-19 at 12 32 07 pm](https://cloud.githubusercontent.com/assets/11947677/13186860/58acc0ee-d705-11e5-8b50-04cc1e0b9dd3.png)
![screen shot 2016-02-19 at 12 32 19 pm](https://cloud.githubusercontent.com/assets/11947677/13186866/5c121a7c-d705-11e5-929c-8504b190e38b.png)
![screen shot 2016-02-19 at 12 32 33 pm](https://cloud.githubusercontent.com/assets/11947677/13186907/873e1642-d705-11e5-8bb9-02e8cf14573e.png)
And if moved, it will jump back to the right position and won't be able to be dragged past that point

**Comment by elisemorgan** [comment] 2016-02-22 18:14
@aadish The original issue reported by @phet-steele is resolved. While the bounds shift, the figure is not lost in any way. Assigning to @ariel-phet to confirm that this can be closed.

**Comment by ariel-phet** [comment] 2016-02-23 17:26
All seems resolved in latest pull, closing

**Closed by ariel-phet** 2016-02-23 17:26 UTC
