### ISSUE TITLE
Sim doesn't open in IE

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-force-lab#192] opened 2019-11-08 19:49 UTC
Loading bar does not start to progress.  Error shown below.
For https://github.com/phetsims/QA/issues/455
![error](https://user-images.githubusercontent.com/41024075/68506139-23271c80-0226-11ea-88c4-c2e34be4c888.png)

**Comment by jbphet** [comment] 2019-11-08 21:08
The built version of Number Line: Integers is also not currently loading in IE, and I did a bit of digging and it looks like something has broken in the build process.  I'm seeing this in the `_debug` file:

```  
const privatePredicate = () => {
    // Trying to access localStorage may fail with a SecurityError if cookies are blocked in a certain way.
    // See https://github.com/phetsims/qa/issues/329 for more information.
   .
   .
   .
```

This is in `QueryStringMachine`, and IE is barfing on the ES6 syntax.

I'm not sure if this is the same root cause, but I thought I'd mention it in case it helps.

**Comment by pixelzoom** [comment] 2019-11-08 21:23
`privatePredicate` was added to QueryStringMachine by me on 3/7/19. It’s been there awhile and was vetted, so unlikely to be the cause.

**Comment by KatieWoe** [comment] 2019-11-08 22:38
Impacts phet-io as well

**Comment by zepumph** [comment] 2019-11-08 23:16
This is a general issue that has to do with the es6 "spread operator" and effects every sim. It will be handled generall by https://github.com/phetsims/perennial/issues/153. Since this is just a dev test, I feel fine closing.

**Closed by zepumph** 2019-11-08 23:16 UTC
Labels: type:bug
