### ISSUE TITLE
Automated Testing Sim Error (3/14/2017 10:00 AM)

### ISSUE THREAD

**Issue by phet-steele** [phetsims/gravity-force-lab#88] opened 2017-03-14 17:00 UTC
Only occurs in basics version, but from code in this repo.

In basics version:
1. Check Constant Radius
2. Drag m1 all the way right

```
Error: formatForceReadout requires a decimal value
    at Array.redrawForce (http://phettest.colorado.edu/gravity-force-lab/js/gravity-force-lab/view/MassNode.js?bust=1489509038217:192:17)
    at Emitter.emit2 (http://phettest.colorado.edu/axon/js/Emitter.js?bust=1489509038217:147:49)
    at DerivedProperty._notifyObservers (http://phettest.colorado.edu/axon/js/Property.js?bust=1489509038217:208:29)
    at DerivedProperty._setAndNotifyObservers (http://phettest.colorado.edu/axon/js/Property.js?bust=1489509038217:197:14)
    at DerivedProperty.set (http://phettest.colorado.edu/axon/js/Property.js?bust=1489509038217:141:16)
    at Array.listener (http://phettest.colorado.edu/axon/js/DerivedProperty.js?bust=1489509038217:76:34)
    at Emitter.emit2 (http://phettest.colorado.edu/axon/js/Emitter.js?bust=1489509038217:147:49)
    at Property._notifyObservers (http://phettest.colorado.edu/axon/js/Property.js?bust=1489509038217:208:29)
    at Property._setAndNotifyObservers (http://phettest.colorado.edu/axon/js/Property.js?bust=1489509038217:197:14)
    at Property.set (http://phettest.colorado.edu/axon/js/Property.js?bust=1489509038217:141:16)
```

**Comment by jessegreenberg** [comment] 2017-03-22 20:45
The above commit fixes this issue, closing.

**Comment by phet-steele** [comment] 2017-03-24 19:30
@jessegreenberg bayes still occasionally reports this error. I cannot reproduce it by hand with the way described above, though.

**Comment by jessegreenberg** [comment] 2017-03-24 22:50
Thanks @phet-steele, perhaps there is another way to get the distance to zero now.

**Comment by jessegreenberg** [comment] 2017-03-24 22:56
The above commit hides the mockup slider, maybe we will see the error with more consistency now?

**Comment by jessegreenberg** [comment] 2017-03-25 02:14
@phet-steele told me how to reproduce (thanks!!)

- move m1 all the way to the left
- move m2 to m1's initial position (use the mockup image to guide with query parameter ?mockup)
- press Reset All button

The problem is that the reset all button calls these in order in InverseSquareLawModel.
```js
      this.object1.reset();
      this.object2.reset();
```

When object 1 is reset, it is moved on top of object 2 (since object 2 was moved to object 1's initial position), and we proceed to calculate the force while distance is zero. @mbarlow12 would you mind looking into this?  One solution could be to add a flag that disables force calculations during the ```reset``` function in ```InverseSquareLawModel```.

**Comment by mbarlow12** [comment] 2017-03-25 04:24
Sure thing. I'll have a closer look into it tomorrow.

Thanks,
Michael

**Comment by mbarlow12** [comment] 2017-08-04 19:06
Closing.

**Closed by mbarlow12** 2017-08-04 19:06 UTC
Labels: type:automated-testing
