### ISSUE TITLE
Toggling Scientific Notation shifts pullers, panels, resetAllButton by a px

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gravity-force-lab#101] opened 2018-07-17 21:01 UTC
Observed on master on latest Mac/Chrome.

Turning on scientific notation shifts the panels, resetAllButton, and pullers up about a pixel. It's a really subtle shift, but the ruler can help make the shift a bit more obvious.

![image](https://user-images.githubusercontent.com/8419308/42845073-151a4d06-89d2-11e8-91bb-404a1e012e53.png)
![image](https://user-images.githubusercontent.com/8419308/42845085-1e82bf86-89d2-11e8-9c1c-58dba0a6ea2f.png)

**Comment by arouinfar** [comment] 2018-07-18 20:42
What's a bit puzzling is scientific notation shifts things <i>up</i>. I would expect the opposite, given that the superscripts make the strings a bit taller, effectively pushing everything else down.

**Comment by terracoda** [comment] 2019-08-02 14:53
@arouinfar, I don't see any shifting. Do you still see something? There are have been many changes to the sim.

**Comment by arouinfar** [comment] 2019-08-02 18:12
Yes, it still happens when on master. It's subtle, but the panels all shift when toggling scientific notation.

If you click on this .gif to open it in a new window, the shift will be a bit more obvious.
![Untitled](https://user-images.githubusercontent.com/8419308/62390041-9251ee00-b51e-11e9-8b99-0a05d3c77109.gif)

**Comment by terracoda** [comment] 2019-08-02 21:09
Oh, I see it. Yes, it is very subtle ;-)

**Comment by zepumph** [comment] 2019-10-08 01:44
I poked around with this a bit, and I didn't find anything. I did note though that it does seem to happen in GFLB as well.

**Comment by KatieWoe** [comment] 2020-02-17 20:47
The mass labels can move up and down while moving their sliders. May just be a problem with firefox, hard to tell. For https://github.com/phetsims/QA/issues/480
![bouncingmass](https://user-images.githubusercontent.com/41024075/74685508-020e8a00-518c-11ea-8eb4-af6fa114b3c5.gif)

**Comment by pixelzoom** [comment] 2020-08-14 04:17
Perhaps there’s a LayoutBox (VBox, HBox) that’s resizing?

**Comment by pixelzoom** [comment] 2020-08-14 04:18
Over in #268, I reported that this happens when selecting different radio buttons, and it's very pronounced, not subtle.

Perhaps there’s a LayoutBox (VBox, HBox) that’s resizing?

**Comment by pixelzoom** [comment] 2021-07-22 22:04
Something similar happens in ph-scale with Chrome, all platforms. See https://github.com/phetsims/ph-scale/issues/226.

**Comment by pixelzoom** [comment] 2021-07-23 00:15
Over in phetsims/ph-scale#226, I determined that adding `preventFit: true` to ANY Node on the screen fixes this problem.  For example, add it to `resetAllButton` in GravityForceLabScreenView.js, and you'll see that the problem goes away. I have no idea why.

**Comment by zepumph** [comment] 2021-07-23 13:28
Thanks! That is really helpful to hear. I appreciate you telling me.

**Comment by zepumph** [comment] 2021-07-23 13:36
I added it above, to the originally reported component. I can't reproduce this bug now, and I don't see it in GFLB. I'm ready to close this. Please reopen if there is anything else.

**Comment by pixelzoom** [comment] 2021-07-23 19:42
Sorry to reopen this. But see @jonathanolson's recommendations in https://github.com/phetsims/ph-scale/issues/226#issuecomment-885817011, the most important line being:
> On the ResetAllButton sounds good, but placing preventFit on the content that moves might be more appropriate, in case layer splits are added in the future.

I may still set it on ResetAllButton in ph-scale, since it's trivial.  

Up to you whether you want to change anything here, but wanted you to be aware of this recommendation.

**Comment by pixelzoom** [comment] 2021-09-29 16:31
@zepumph The new recommendation is to add option `preventFit: true` to the ScreenView, see https://github.com/phetsims/scenery/issues/1289#issuecomment-930336097.  You may want to adjust this sim accordingly.

**Comment by zepumph** [comment] 2021-09-30 17:08
Thanks!

**Comment by zepumph** [comment] 2021-09-30 17:15
After reviewing, https://github.com/phetsims/inverse-square-law-common/commit/52b531d47f21c20d25536e9dc8975edb4f820891 seems to be the best solution to me. I haven't seen this effecting any other components in the sim. @jonathanolson mentioned that fitting helps performance, so I like the idea that we only put preventFit on the Node that we needed, instead of the `ScreenView` of each sim.  This issue is still solved by the commit already made. I'm going to re-close this issue.

**Closed by zepumph** 2021-09-30 17:15 UTC
Labels: priority:2-high
