### ISSUE TITLE
Beyond-edge responses for mass control sliders?

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab#206] opened 2019-11-20 18:00 UTC
@zepumph, we implemented these beyond-edge responses for GFLB.
I'd like to do the same for GFL regular. I didn't hear them yesterday when I tested. 2.2.0-dev.18

**Comment by zepumph** [comment] 2019-11-26 00:20
Can you be a bit more specific here? What device were you testing with? This is not something that we support for gesture iOS because the sim receives no events when this happens. The user tries to move beyond the max/min of the slider and the just repeats the current value without giving us anything. I was able to reproduce this problem on my iPad.

If this was not from a gesture device, then it would be good to hear more about it.

**Comment by zepumph** [comment] 2019-11-26 00:26
Oh! Also @jessegreenberg found original conversation about this same thing over in https://github.com/phetsims/gravity-force-lab-basics/issues/185#issuecomment-545180225, so I'll add it here.

**Comment by zepumph** [comment] 2019-11-26 18:01
@terracoda and I found that this was working as expected on all our devices. @terracoda was also already aware that this feature didn't work on mobile devices. Closing

**Closed by zepumph** 2019-11-26 18:01 UTC
Labels: dev:a11y, type:question
