### ISSUE TITLE
The sim suddenly enlarges on iPad 3 iOS 9

### ISSUE THREAD

**Issue by jbphet** [phetsims/gravity-force-lab#39] opened 2015-10-28 23:25 UTC
I was testing the master version of this sim after making some changes, and on Disessa, which is an iPad 3 running iOS 9.0.2, I kept hitting a case where the screen would suddenly appear to zoom way in.  After a bunch of testing to try to find a way to duplicate consistently, I finally figured out that it happens regardless of what the user does.  So, to duplicate this, all you have to do is load the sim and wait about 25 seconds.  Here's a screenshot of what it looks like right after it enlarges:

![gfl-enlarged](https://cloud.githubusercontent.com/assets/3082831/10805917/26e04d46-7d97-11e5-858e-88f9cd805f9f.png)

I didn't find any obvious ways to get out of this situation, so I tried reloading.  The first reload looks like this:
![gfl-tiny](https://cloud.githubusercontent.com/assets/3082831/10805952/6380505c-7d97-11e5-8d53-2e0db2ccc26a.png)

After reloading a second time, the sim behaves normally for the same 25 seconds or so, and then enlarges again.

**Comment by jbphet** [comment] 2015-10-28 23:26
Seems scenery-ish to me, so I'll assign to @jonathanolson for now and he and I can take a look when he is in tomorrow.

**Comment by pixelzoom** [comment] 2015-10-29 18:59
Dev meeting:  test on iOS 9.1.

**Comment by jbphet** [comment] 2015-10-29 22:58
I upgraded the iPad 3 (Disessa) to 9.1, and the problem did *not* go away.

**Comment by jbphet** [comment] 2015-10-29 23:11
Tested this on an iPad 2 (Tycho) running iOS 9.0 and the problem occurs there too.  The problem does *not* occur on an iPad 2 (@jbphet's test iPad) running iOS 8.3.

**Comment by jonathanolson** [comment] 2015-10-30 03:46
Doesn't occur in built sims, and is fixed with require.js-mode by including some of the standard production template headers. Specifically this one prevents the behavior:
```html
<meta name="viewport" content="initial-scale=1,user-scalable=no,maximum-scale=1"/>
```

I'll briefly dig a bit deeper to try to find out the root cause. Also, there is a noticeable gap on the bottom and right where the navbar doesn't extend to the screen edge fully (it's white), and it's probably Safari trying to do an auto-detection of how to display the content (this sim in particular triggers something), and it changes it once it thinks the page is fully loaded.

**Comment by jonathanolson** [comment] 2015-10-30 04:29
This looks like it was triggered by the length of the heartbeat div. After the sim resizes incorrectly, removing the heartbeat div also brought it back to normal.

I added more advanced styling so that it wouldn't affect the layout code, and tested OS X 10.11 Safari and iOS 9.1 Safari (MBA and iPad3), and 4-5 minute delays didn't trigger the symptoms of https://github.com/phetsims/joist/issues/140.

@samreid, would you be able to review my changes to make sure this didn't break the heartbeat div's purpose?

**Comment by samreid** [comment] 2015-11-03 14:27
Testing graphing lines with this line commented out reveals a problem after 60 sec in Safari OS X Version 9.0.1 (11601.2.7.2)

```js
this.heartbeatDiv.innerHTML = Math.random();
```

Re-enabling the above line, with the styles applied to the heartbeat div the pause goes away.  So I think these styles are safe and good.  Closing.

**Closed by samreid** 2015-11-03 14:27 UTC
