### ISSUE TITLE
When launching the sim from Studio or the Wrapper index on Firefox, it initially fails to play audio

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/gravity-force-lab#260] opened 2020-03-03 20:31 UTC
<b>Test Device</b>

Windows 10 laptop

<b>Operating System</b>

Windows 10

<b>Browser</b>

Firefox

<b>Problem Description</b>

For https://github.com/phetsims/QA/issues/485

When launching the sim either through studio or using the launch button on the wrapper index, firefox fails to play any sound initially. After switching tabs away from and back to the launched sim sound works

<b>Steps to Reproduce</b>

1. Open Studio
2. Launch the simulation
3. Manipulate the simulation
4. Switch to a different tab
5. Return to the tab of the launched sim
6. Manipulate the simulation

**Comment by zepumph** [comment] 2020-03-03 21:35
I think this is a duplicate of https://github.com/phetsims/phet-io-wrappers/issues/324. @loganbraywork please reopen if you disagree.

**Closed by zepumph** 2020-03-03 21:35 UTC
Labels: type:bug
