### ISSUE TITLE
Can't move ruler with mobile VO

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-force-lab#238] opened 2020-01-29 22:41 UTC
For https://github.com/phetsims/QA/issues/471. Tested using mobile VO on latest iPadOS.
I noticed that there doesn't seem to be anyway to move the ruler around when using mobile VO. This isn't a massive problem, but the scene description does still indicate that it is possible.

**Comment by KatieWoe** [comment] 2020-01-29 23:20
@zepumph explained how this is done to me and I was able to do it. However, there is a noticeable amount of lag between doing the double tap and being able to move your finger. If you start too soon it swipes through different options your finger passes over.

**Comment by zepumph** [comment] 2020-01-31 03:23
I'm not really sure what to do here. @jessegreenberg have you noticed this lag like I have? Is there anything to be done?

**Comment by terracoda** [comment] 2020-01-31 03:32
It works nicely on my iPhone 7.

**Comment by zepumph** [comment] 2020-01-31 03:47
@terracoda I definitely have to wait >.5 seconds between the double tab and when VO registers the double tap. For super user it is definitely noticeable. Do you experience that also?

**Comment by jessegreenberg** [comment] 2020-01-31 15:49
I experience this delay too but I am pretty sure it is expected. The gesture is not just "double tap" it is "double tap and hold". As mentioned in https://support.apple.com/guide/iphone/learn-voiceover-gestures-iph3e2e2281/ios you have to wait until you hear three rising tones, then you can drag the object. See the "Drag a slider" entry.

**Comment by terracoda** [comment] 2020-01-31 16:05
Yes, I have a triple tone and a delay, too. As soon as the tone has played it is safe to drag. It seems to be intentional, and not too long to me on the iPhone7.

**Comment by terracoda** [comment] 2020-01-31 17:05
I agree with @jessegreenberg, I think this delay is expected behaviour.

**Comment by zepumph** [comment] 2020-02-03 19:03
From https://github.com/phetsims/gravity-force-lab/issues/238#issuecomment-580788088:

![image](https://user-images.githubusercontent.com/6856943/73681321-8e885b00-466a-11ea-8b07-46559a4efbc3.png)

With that in mind I think we should close this. Over to @KatieWoe to read over and close if all is good.

**Closed** 2020-02-03 19:51 UTC
Labels: status:ready-for-review, type:a11y-bug, type:bug
