### ISSUE TITLE
entire screen shifts around when switching between radio buttons

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gravity-force-lab#268] opened 2020-08-13 21:26 UTC
There's a significant layout problem in this sim.

1. Start the unbuilt sim in master
2. Toggle between the "Decimal Notation" and "Scientific Notation" radio buttons
3. Watch just about everything on the screen shift around

**Comment by zepumph** [comment] 2020-08-14 01:32
Duplicate of https://github.com/phetsims/gravity-force-lab/issues/101, closing. @pixelzoom do you have any thoughts or ideas about what a culprit of this may be? If so it would be awesome if you could note in that other issue. I poked around for a while but couldn't discover the root cause easily.

**Closed by zepumph** 2020-08-14 01:32 UTC
Labels: type:bug

**Comment by pixelzoom** [comment] 2020-08-14 04:16
Perhaps there’s a LayoutBox (VBox, HBox) that’s resizing?
